repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0
    hooks:
      - id: terraform_providers_lock
        types: ["file", "non-executable", "terraform", "text"]

      - id: terraform_fmt
        types: ["file", "non-executable", "terraform", "text"]

      - id: terraform_validate
        types: ["file", "non-executable", "terraform", "text"]

      - id: terraform_tflint
        types: ["file", "non-executable", "terraform", "text"]

      - id: terraform_checkov
        types: ["file", "non-executable", "terraform", "text"]

  - repo: https://github.com/getindata/py-pre-commit-hooks
    rev: v0.2.1
    hooks:
      - id: pyspelling-docker
        types: ["file", "markdown", "non-executable", "text"]